# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-agency
url    : "https://valientetechnologies.com"
baseurl: ""

title      : Valiente Technologies
email      : info@valiente.com.tr
description: "Antalya'nın ilk ve tek siber güvenlik şirketi. Sızma (penetrasyon) testi, web ve mobil uygulama güvenliği, bulut güvenliği ve ofansif güvenlik hizmetleri. Valiente Technologies ile dijital varlıklarınızı profesyonelce koruyun."
author     : Valiente Technologies
social:
  linkedin: https://www.linkedin.com/company/valientetechnologies
  instagram: https://www.instagram.com/valientetechnologies
  github: https://github.com/ValienteTechnologies
# Polyglot multilanguage
languages: ["tr", "en"]
default_lang: "tr"
exclude_from_localization:
  - assets
  - CNAME
  - robots.txt
  - scripts
parallel_localization: true
logo:
  path: /assets/img/valiente/valientetitle.svg

analytics:
  google: G-FF9YHPMVJL

collections:
  pages:
    output: true
    permalink: /:name/

plugins:
  - jekyll-polyglot
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - scripts/

markdown: kramdown

strict_front_matter: true

formspree_form_path: "f/xwpbqjer"
